name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      working-directory: ./weli_writer_android
      run: chmod +x gradlew

    - name: Build Project
      working-directory: ./weli_writer_android
      run: ./gradlew build

    - name: Build Release AAB      // 1
      working-directory: ./weli_writer_android
      run: ./gradlew bundleRelease

    - name: Sign AAB
      uses: r0adkll/sign-android-release@v1
      working-directory: ./weli_writer_android
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Check output
      working-directory: ./weli_writer_android/app/build/outputs/bundle/release
      run: ls -la
